version: "2"

services:
  cuckoo:
    privileged: true
    image: cuckoo-docker-devel:2.0.7
    build:
      context: .
      dockerfile: src/Dockerfile.devel
    volumes:
      - ./cuckoo:/opt/cuckoo

